### ISSUE TITLE
Enforcing signing

### ISSUE THREAD

**Issue by jim-parry** [lonnieezell/CodeIgniter4#107]
We are starting to get contributions from the community.
Should we start enforcing signing, eg GPG?

**Comment by lonnieezell** [comment]
That would mean I need to get in that habit, too, wouldn't it? :)

I believe the original intent of that requirement was to sign-off that they were giving their original code and making it available under what license EllisLab had it under. Since we're not saying that, is there a need for signing off? Seems like another barrier for contributions that doesn't add anything for us right now.

**Comment by jim-parry** [comment]
It is intended to prove the provenance of contributed code.
I have a PR in progress to test the commiting with a GPG key.

**Comment by jim-parry** [comment]
I think at a minimum we need to enforce reasonable descriptions, all the orhter stuff in the contributing guideline (test if needed, docs if needed, user guide if needed), and at a minimum a "signoff", even if it isn't GPG. We have had a few sloppy commits over the last day or two, adn I think we need to nip that.

**Comment by jim-parry** [comment]
The original intent, when I talked to Ellis back when was both to make sure EllisLab could use it, as well as to establish provenance going forward with version 3.
Quoting narf.. "We do formally require this, but people being people made it an afterthought even for us."

**Comment by lonnieezell** [comment]
> I think at a minimum we need to enforce reasonable descriptions, all the orhter stuff in the contributing guideline (test if needed, docs if needed, user guide if needed), 

Couldn't agree more. 

> and at a minimum a "signoff", even if it isn't GPG.

Unconvinced it's necessary since every commit is attached to an account which is recorded during the commit, so ownership/provenance is already recorded.
