### ISSUE TITLE
SYSDIR

### ISSUE THREAD

**Issue by exbit** [lonnieezell/CodeIgniter4#25]
windows OS
define('SYSDIR', trim(strrchr(trim(BASEPATH, '/'), '/'), '/'));
var_dump(SYSDIR);
string(0) "" 

Fix:
define('SYSDIR', trim(strrchr(trim(str_replace('\\', '/', BASEPATH), '/'), '/'), '/'));

**Comment by narfbg** [comment]
This constant is useless, I'm voting to remove it.

**Comment by lonnieezell** [comment]
I agree with @narfbg. In the 10 or so years that I've been working with CI, I don't think I've ever found a need for that. And it's handled by the $systemFolder variable if you want to change it.

**Comment by lonnieezell** [comment]
It's been removed.

**Comment by sv3tli0** [comment]
I think that the same remove can be made and on other constants. Path Class is a lot better choice to register and handle paths..

**Comment by lonnieezell** [comment]
I don't see a path class being beneficial here. The way CI has always done it is simple, by creating constants for paths that are constant. They're available sitewide. And they use less resources than a class would.

**Comment by sv3tli0** [comment]
I can't give any 100% important reason to have class instead of just constants. 
But at least what I understand from OOP developement, hard coded constants are not really beautiful solution. 

Instead all over the code to check if file_exists(SOMEPATH. 'folder/file') and to require it.. 
You can just use 1 already loaded resource to get the existing path of the file which you need and if it doesn't you will get proper exception/error (not existing no permissions and etc).. 

Of course this has something to do and with the Loaders..

**Comment by lonnieezell** [comment]
Like anything else, OOP design can be taken to extremes it really doesn't need to be. 

In this case, you're right, that's more to do with a loader, or some other class. But if you go the route of creating OOP wrappers for all of PHP's non-OOP functions, things get a little crazy. :) In this case, your example, while a valid function (not necessarily requiring an entire class, but could be ...) would replace `if file_exists` calls with `try/catch blocks` throughout the code, which can harm performance, and isn't anymore beautiful when all you want to do is see `if file exists`....

I'm not saying your class idea doesn't have certain appeals for different situations, but for this one, I think it's overkill and complicates things instead of simplifies them.
