### ISSUE TITLE
Reserved method name

### ISSUE THREAD

**Issue by jim-parry** [lonnieezell/CodeIgniter4#76]
Session/SessionInterface has function 'unset', but that is a reserved name in PHP7.
This propagates to Session/Session.

It doesn't look like the method is called anywhere, though there are lots of calls to the global function 'unset'.

Should the method be renamed?

**Comment by lonnieezell** [comment]
Someone else brought this up before too. :) 

That's actually what it's currently using in CI3, and matches the naming scheme of the other methods. The `unset` method of a class doesn't class with a standalone function name.

**Comment by jim-parry** [comment]
Hmmm. The latest NetBeans, with PHP7 support, flags that as an error.
If it isn't used anywhere, do we need it?

**Comment by lonnieezell** [comment]
Um... it's how the users unset data from the session that they've set. So, the framework doesn't use it, but the users do. :)

**Comment by jim-parry** [comment]
We could be compliant with the PHP reserved name list if we changed the "unset" method name.
For instance, java.util.Map (comparable container) uses get/put/remove where we use get/set/unset.
What do you think of having get, set & put, and remove? "put" would be alias for set.

**Comment by jim-parry** [comment]
Another thing I notice is that we have set, setTempdata and setFlashdata. The latter two can take a key & value, OR an associative array with keys & related values implied. This feels like the PHP equivalent of an overloaded method in Java.

It looks like the same is expected of "set", though that isn't spelled out in the docs ... will fix :)

**Comment by lonnieezell** [comment]
While I don't 100% think it's necessary to change them, it's not a bad idea. I mean, it has worked throughout all of CI 2 and 3 that way so there's no technical reason to - at the moment. But, quoting from the [PHP reserved keywords page](http://php.net/manual/en/reserved.keywords.php): 

> You cannot use any of the following words as constants, class names, function or method names.

So it's probably best to rename them now just in case the interpreter decides to enforce that at some point.

I'm fine with `get`, `set`, and `remove`, but think that aliasing in `put` is unnecessary and confusing. And set is used throughout the framework and I really don't feel like changing everything. :) We will have to keep an eye out for other places where we have methods with similar roles (cache layer will have this, and probably others) so that we can keep a consistent naming scheme.

**Comment by lonnieezell** [comment]
> Another thing I notice is that we have set, setTempdata and setFlashdata. The latter two can take a key & value, OR an associative array with keys & related values implied. This feels like the PHP equivalent of an overloaded method in Java.

You are correct. And it's always been used in the query builder that way too. I don't generally have a problem with it in these cases.

**Comment by jim-parry** [comment]
Ok - will prep a PR for unset->remove, and update the API docs for these.

**Comment by jim-parry** [comment]
I think this can be closed - methods have been renamed & docs updated.
